# Generated by Django 5.2.7 on 2025-10-09 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
