# Generated by Django 5.2.7 on 2025-10-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
