# Generated by Django 5.2.7 on 2025-10-13 03:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('user', 'link')},
        ),
    ]
