# Generated by Django 5.2.7 on 2025-10-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_qrcode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
