# Generated by Django 5.2.7 on 2025-10-13 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_qrcode_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'QR Code', 'verbose_name_plural': 'QR Codes'},
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to=settings.AUTH_USER_MODEL),
        ),
    ]
