# Generated by Django 4.2 on 2025-10-16 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_qrcode_options_alter_qrcode_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='utils.qrcode')),
            ],
            options={
                'verbose_name': 'QR Scan',
                'verbose_name_plural': 'QR Scans',
                'unique_together': {('qr_code', 'ip_address', 'date')},
            },
        ),
    ]
