# Generated by Django 4.2 on 2025-10-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_qrscan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='device_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('qr_code', 'device_hash', 'date')},
        ),
    ]
