# Generated by Django 4.2 on 2025-10-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_qrscan_unique_together_qrscan_device_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrscan',
            options={},
        ),
        migrations.RenameField(
            model_name='qrscan',
            old_name='device_hash',
            new_name='device_uuid',
        ),
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('qr_code', 'device_uuid', 'date')},
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
