# Generated by Django 4.2 on 2025-10-16 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_alter_qrscan_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='qrscan',
            name='date',
        ),
    ]
