# Generated by Django 4.2 on 2025-10-16 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_alter_qrscan_unique_together_qrscan_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('qr_code', 'device_uuid', 'date')},
        ),
        migrations.RemoveField(
            model_name='qrscan',
            name='created',
        ),
    ]
