# Generated by Django 4.2 on 2025-10-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_qrscan_date_alter_qrscan_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrScan',
        ),
    ]
