# Generated by Django 4.2 on 2025-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_delete_qrscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
