# Generated by Django 4.2 on 2025-10-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_qrcode_scan_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='scan_count',
        ),
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='utils.qrcode')),
            ],
            options={
                'verbose_name': 'QR Scan',
                'verbose_name_plural': 'QR Scans',
            },
        ),
    ]
