# Generated by Django 4.2 on 2025-10-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_remove_qrcode_scan_count_qrscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrscan',
            name='date',
        ),
    ]
