# Generated by Django 4.2 on 2025-10-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_remove_qrscan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='last_scanned_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QrScan',
        ),
    ]
