# Generated by Django 5.2.7 on 2025-10-09 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
