# Generated by Django 5.2.7 on 2025-10-10 04:42

import django.core.validators
import izgora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp']), izgora.models.check_image_size]),
        ),
    ]
