# Generated by Django 5.2.7 on 2025-10-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0003_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImages',
        ),
    ]
