# Generated by Django 5.2.7 on 2025-10-10 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0004_delete_categoryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
