# Generated by Django 5.2.7 on 2025-10-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0006_alter_category_created_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
