# Generated by Django 5.2.7 on 2025-10-13 10:00

import django.core.validators
import izgora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0007_category_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp']), izgora.models.check_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), izgora.models.check_image_size]),
        ),
    ]
