# Generated by Django 5.2.7 on 2025-10-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0009_alter_productimage_image_productvariants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='diametr',
            new_name='diameter',
        ),
    ]
