# Generated by Django 5.2.7 on 2025-10-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0010_rename_diametr_productvariants_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
