# Generated by Django 5.2.7 on 2025-10-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0011_alter_productvariants_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='diameter',
            new_name='diametr',
        ),
    ]
