# Generated by Django 5.2.7 on 2025-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0012_rename_diameter_productvariants_diametr'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
