# Generated by Django 4.2 on 2025-10-14 11:58

import django.core.validators
from django.db import migrations, models
import izgora.models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0013_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), izgora.models.check_image_size]),
        ),
    ]
