# Generated by Django 4.2 on 2025-10-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
