# Generated by Django 4.2 on 2025-10-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izgora', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_slug'),
        ),
    ]
